"""
Tree Ontology — hierarchical problem/method/insight trees.

Problems, methods, and insights form proper tree structures instead of flat lists.
This enables recursive decomposition (a problem has sub-problems) and
method composition (a method is composed of sub-methods).
"""
import json
from typing import List, Dict, Any, Optional
from enum import Enum
from pydantic import BaseModel, Field


class NodeStatus(str, Enum):
    UNSOLVED = "unsolved"
    ACTIVE = "active"
    PARTIAL = "partial"
    SOLVED = "solved"


class ProblemNode(BaseModel):
    """A problem in the research tree."""
    id: str
    name: str
    definition: str = ""
    domain: str = "general"
    resolution_status: str = "active"
    constraints: str = ""
    evaluation_metrics: str = ""
    parent_id: Optional[str] = None
    children_ids: List[str] = Field(default_factory=list)
    depth: int = 0
    solved_by_methods: List[str] = Field(default_factory=list)
    value_score: float = 50.0
    papers: List[str] = Field(default_factory=list)
    year: Optional[int] = None


class MethodNode(BaseModel):
    """A method in the method tree."""
    id: str
    name: str
    definition: str = ""
    domain: str = "general"
    mechanism: str = ""
    assumptions: str = ""
    limitations: str = ""
    parent_id: Optional[str] = None
    children_ids: List[str] = Field(default_factory=list)
    depth: int = 0
    solves_problems: List[str] = Field(default_factory=list)
    composed_of: List[str] = Field(default_factory=list)
    improves_upon: Optional[str] = None
    value_score: float = 50.0
    papers: List[str] = Field(default_factory=list)
    year: Optional[int] = None


class InsightNode(BaseModel):
    """An innovation insight generated by the system."""
    id: str
    type: str = "cdt"  # cdt, shf, mc, tf, ch, rgi
    title: str = ""
    rationale: str = ""
    hypothesis: str = ""
    experiment_design: str = ""
    confidence: float = 0.0
    composite_score: float = 0.0
    status: str = "hypothesis"
    source_node_ids: List[str] = Field(default_factory=list)
    evidence_claim_ids: List[str] = Field(default_factory=list)
    agent_debate_log: Dict[str, Any] = Field(default_factory=dict)


class TreeOntologyManager:
    """
    Manages hierarchical trees for problems, methods, and insights.
    Backed by LocalGraphDB for persistence.
    """

    def __init__(self, graph_db=None):
        from app.database.local_graph import get_local_graph_db
        self.graph_db = graph_db or get_local_graph_db()
        self._node_cache: Dict[str, Any] = {}

    def create_problem(self, problem_id: str, name: str, parent_id: Optional[str] = None,
                       domain: str = "general", **kwargs) -> ProblemNode:
        """Create a problem node, optionally as a child of another problem."""
        depth = 0
        if parent_id:
            parent = self.get_problem(parent_id)
            if parent:
                depth = parent.depth + 1
                # Store parent-child relation in graph
                self.graph_db.create_relation(parent_id, problem_id, "HAS_SUB_PROBLEM")

        problem = ProblemNode(
            id=problem_id, name=name, parent_id=parent_id,
            depth=depth, domain=domain, **kwargs
        )
        self.graph_db.create_problem(problem.model_dump())
        self._node_cache[problem_id] = problem
        return problem

    def create_method(self, method_id: str, name: str, parent_id: Optional[str] = None,
                      domain: str = "general", **kwargs) -> MethodNode:
        """Create a method node, optionally as a sub-method."""
        depth = 0
        if parent_id:
            parent = self.get_method(parent_id)
            if parent:
                depth = parent.depth + 1
                self.graph_db.create_relation(parent_id, method_id, "COMPOSED_OF")

        method = MethodNode(
            id=method_id, name=name, parent_id=parent_id,
            depth=depth, domain=domain, **kwargs
        )
        self.graph_db.create_method(method.model_dump())
        self._node_cache[method_id] = method
        return method

    def create_insight(self, insight_id: str, title: str, paradigm: str,
                       **kwargs) -> InsightNode:
        """Create an insight node."""
        insight = InsightNode(
            id=insight_id, title=title, type=paradigm, **kwargs
        )
        self.graph_db.create_insight(insight.model_dump())
        self._node_cache[insight_id] = insight
        return insight

    def get_problem(self, problem_id: str) -> Optional[ProblemNode]:
        """Get a problem by ID."""
        if problem_id in self._node_cache:
            cached = self._node_cache[problem_id]
            if isinstance(cached, ProblemNode):
                return cached

        data = self.graph_db.get_problem(problem_id)
        if not data:
            return None
        # Map existing graph DB fields to ProblemNode
        node = ProblemNode(
            id=data.get('id', problem_id),
            name=data.get('name', ''),
            definition=data.get('definition', ''),
            domain=data.get('domain', 'general'),
            resolution_status=data.get('resolution_status', 'active'),
            constraints=data.get('constraints', ''),
            evaluation_metrics=data.get('evaluation_metrics', ''),
            value_score=data.get('value_score', 50.0),
            papers=data.get('papers', []),
            year=data.get('year')
        )
        self._node_cache[problem_id] = node
        return node

    def get_method(self, method_id: str) -> Optional[MethodNode]:
        """Get a method by ID."""
        if method_id in self._node_cache:
            cached = self._node_cache[method_id]
            if isinstance(cached, MethodNode):
                return cached

        data = self.graph_db.get_method(method_id)
        if not data:
            return None
        node = MethodNode(
            id=data.get('id', method_id),
            name=data.get('name', ''),
            definition=data.get('definition', ''),
            domain=data.get('domain', 'general'),
            mechanism=data.get('mechanism', ''),
            value_score=data.get('value_score', 50.0),
            papers=data.get('papers', []),
            year=data.get('year')
        )
        self._node_cache[method_id] = node
        return node

    def get_insight(self, insight_id: str) -> Optional[InsightNode]:
        """Get an insight by ID."""
        if insight_id in self._node_cache:
            cached = self._node_cache[insight_id]
            if isinstance(cached, InsightNode):
                return cached

        data = self.graph_db.get_insight(insight_id)
        if not data:
            return None
        node = InsightNode(**data)
        self._node_cache[insight_id] = node
        return node

    def get_subtree(self, root_id: str, node_type: str, max_depth: int = 3) -> Dict[str, Any]:
        """Get a subtree rooted at the given node."""
        getter = {
            'problem': self.get_problem,
            'method': self.get_method,
            'insight': self.get_insight
        }.get(node_type)

        if not getter:
            return {}

        root = getter(root_id)
        if not root:
            return {}

        def build_tree(node_id: str, current_depth: int, current_type: str) -> Dict[str, Any]:
            g = {'problem': self.get_problem, 'method': self.get_method}.get(current_type)
            node = g(node_id) if g else None
            if not node or current_depth > max_depth:
                return {"id": node_id, "truncated": True}

            result = {
                "id": node.id,
                "name": node.name,
                "type": current_type,
                "status": getattr(node, 'resolution_status', 'unknown'),
                "depth": node.depth,
                "domain": node.domain,
                "value_score": getattr(node, 'value_score', 50.0),
                "children": []
            }

            for child_id in node.children_ids:
                child_tree = build_tree(child_id, current_depth + 1, current_type)
                if child_tree:
                    result["children"].append(child_tree)

            return result

        return build_tree(root_id, 0, node_type)

    def link_problem_method(self, problem_id: str, method_id: str):
        """Link a method to a problem (method SOLVES problem)."""
        self.graph_db.create_solves_relationship(method_id, problem_id)
        # Update in-memory scores
        problem = self.get_problem(problem_id)
        method = self.get_method(method_id)
        if problem:
            problem.solved_by_methods.append(method_id)
            if problem.resolution_status == 'unsolved':
                problem.resolution_status = 'partial'
        if method:
            method.solves_problems.append(problem_id)

    def compute_value_score(self, node_id: str, node_type: str) -> float:
        """Compute real valueScore for a node."""
        if node_type == 'problem':
            node = self.get_problem(node_id)
            if not node:
                return 50.0
            base_scores = {'solved': 90, 'partial': 65, 'active': 45, 'unsolved': 25}
            score = base_scores.get(node.resolution_status, 45)
            score += min(len(node.solved_by_methods) * 10, 20)
            # Constraints and metrics bonus
            score += min(len(node.constraints) * 2, 10)
            score += min(len(node.evaluation_metrics) * 2, 10)
            return min(score, 100.0)

        elif node_type == 'method':
            node = self.get_method(node_id)
            if not node:
                return 50.0
            score = 50.0
            score += min(len(node.solves_problems) * 15, 30)
            score += min(len(node.composed_of) * 5, 15)
            # Penalize limitations
            score -= min(len(node.limitations) * 3, 15)
            return max(10.0, min(score, 100.0))

        return 50.0
